select * 
from Customer_Behaviour 

--Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) as revenue
from Customer_Behaviour
group by gender
order by revenue

--Q2. Which customer used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from Customer_Behaviour
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from Customer_Behaviour)

--Q3. Which are the top 5 products with the highest average rating?

select top 5 item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
from Customer_Behaviour
group by item_purchased
order by avg(review_rating) Desc;

 --Q4. Compare the average purchase amount between standard express shipping.

 select shipping_type,
 ROUND(AVG(purchase_amount),2)
 from Customer_Behaviour
 where shipping_type IN ('Standard','Express')
 group by shipping_type

 --Q5. Do subscribers customers spend more?compare average spend and total revenue between subscribers and non-subscribers.

 select subscription_status,
 count(customer_id) as total_customers,
 ROUND(AVG(purchase_amount),2) as avg_spend,
 ROUND(SUM(purchase_amount),2) as total_revenue
 from Customer_Behaviour
 group by Subscription_status
 order by total_revenue, avg_spend desc;

 --Q6. Which 5 products have the highest percentage of purchases with discounts applied?

 select top 5 item_purchased,
 ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
 from Customer_Behaviour
 group by item_purchased
 order by discount_rate desc
 
--Q7. Segement customers into New, Returning, and Loyal based on their total number of previuos purchases, and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
from Customer_Behaviour
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment
order by count(*) desc;

--Q8. what are the top 3 most purchased products within each category?
with item_counts as (
select category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from Customer_Behaviour
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from Customer_Behaviour
where previous_purchases > 5
group by subscription_status

--Q10. What is the reveneue contribution of each age group?

select age_group,
SUM(purchase_amount) as total_revenue
from Customer_Behaviour
group by age_group
order by total_revenue desc;